# Забираем шаблоны
include:
  - '/gitlab-ci/template.yml'

# Ставим переменные дочернего пайплайна
variables:
  PROJECT: "BomesWebTelegramBot" # <-- PROJECT: "(Название сервиса)"
  DOCKERNAME: "bomes-webtelegrambot" # <-- DOCKERNAME: "(Имя контейнера)"

# jobs внутри дочернего пайплайна
BomesWebTelegramBot_build:
  extends: .build-template-servises

SleepPipeline:
  extends: .sleep_pipeline