
stages:          # List of stages for jobs, and their order of execution
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

# Шаблон сборки образа 
.build-template-api:
  stage: build
  rules:
    # Если есть изменения, то собираем соответствующий микросервис
    - changes:
        paths:
          - gitlab-ci/**/*
          - Servises/$PROJECT/**/*
      when: always
    # В иных случаях оставляем как manual, чтобы разработчик мог запустить по своему желанию
    - when: manual
  script:
    - echo "Deleting oldest container and image..."
    - docker stop bomes-api || echo "bomes-api is stoped"
    - docker rm bomes-api || echo "bomes-api is removed"
    - echo "Deleting oldest image bomes-api"
    - docker rmi $(docker images | grep bomes-api | awk {print'$3'} | tr -s '\n' ' ') || echo "image bomes-api is removed"
    - cd $PROJECT
    - docker build -t bomes-api .
    - docker run -dit --name bomes-api -p 8000:8000 --net docker_bomes --ip 172.20.1.2 bomes-api
    - echo "Compile complete."

.build-template:
  stage: build
  rules:
    # Если есть изменения, то собираем соответствующий микросервис
    - changes:
        paths:
          - gitlab-ci/**/*
          - Servises/$PROJECT/**/*
      when: always
    # В иных случаях оставляем как manual, чтобы разработчик мог запустить по своему желанию
    - when: manual
  script:
    - echo "Deleting oldest container and image..."
    - docker stop bomes-api || echo "bomes-api is stoped"
    - docker rm bomes-api || echo "bomes-api is removed"
    - echo "Deleting oldest image bomes-api"
    - docker rmi $(docker images | grep bomes-api | awk {print'$3'} | tr -s '\n' ' ') 
    - docker build -t bomes-api .
    - docker run -dit --name bomes-api -p 8000:8000 --net docker_bomes --ip 172.20.1.2 bomes-api
    - echo "Compile complete."

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Deleting oldest container and image..."
    - docker stop bomes-api || echo "bomes-api is stoped"
    - docker rm bomes-api || echo "bomes-api is removed"
    - echo "Deleting oldest image bomes-api"
    - docker rmi $(docker images | grep bomes-api | awk {print'$3'} | tr -s '\n' ' ') 
    - docker build -t bomes-api .
    - docker run -dit --name bomes-api -p 8000:8000 --net docker_bomes --ip 172.20.1.2 bomes-api
    - echo "Compile complete."