# Забираем шаблоны
include:
  - '/gitlab-ci/template.yml'

# Ставим переменные дочернего пайплайна
variables:
  PROJECT: "BomesMailService" # <-- PROJECT: "(Название сервиса)"
  DOCKERNAME: "bomes-mail" # <-- DOCKERNAME: "(Имя контейнера)"

# jobs внутри дочернего пайплайна
BomesMailService_build:
  extends: .build-template-servises